name: continuous-integration

env:
  NODE_version: '20'

on:
  push:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: ${{ env.NODE_version }}
      - name: Test
        run: |
          cd frontend && npm install && npm run build
          cd ../backend && npm install && node -c server.js
          echo "✅ Tests OK"

  deploy:
    needs: test
    runs-on: ubuntu-latest
    # Déploiement uniquement si secrets configurés
    steps:
      - name: Deploy to VPS
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.VPS_IP }}
          username: ${{ secrets.VPS_USER }}
          key: ${{ secrets.VPS_SSH_KEY }}
          script: |
            sudo mkdir -p /var/www/devops-project
            cd /var/www/devops-project
            sudo chmod +x deploy.sh
            sudo ./deploy.sh