name: déploiement

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  # Test et Build
  build:
    runs-on: ubuntu-latest
    
    steps:
      - name: Récupérer le code
        uses: actions/checkout@v4

      - name: Installer Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      # Test Frontend
      - name:  Test Frontend
        working-directory: ./frontend
        run: |
          npm install
          npm run build

      # Test Backend  
      - name:  Test Backend
        working-directory: ./backend
        run: |
          npm install
          node -c server.js

      - name:  Tests OK
        run: echo "Tous les tests sont OK !"